version: "3.9"
services:
  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "subuser"
      POSTGRES_USER: "subuser"
      POSTGRES_PASSWORD: "subuser"
      TZ: "Europe/Moscow"
    volumes:
      - .:/docker-entrypoint-initdb.d